version: 1.0.{build}
branches:
  only:
  - master
image: Visual Studio 2017
configuration: Release
clone_folder: C:\projects\puppeteer-sharp
environment:
  git_access_token:
    secure: FxcQ9C8a/NgcQB5dFdZts6ZWEDT4zMhA4qPQAYwWc7huMmhmTIl1sbFEIaAWQMTL
  matrix:
    - framework: net471
only_commits:
  files:
    - lib/PuppeteerSharp.AspNetFramework/
    - appveyor-fullframework.yml
before_build:
- ps: >-
    dotnet restore .\lib\PuppeteerSharp.AspNetFramework.sln

    New-SelfSignedCertificate -Subject "localhost" -FriendlyName "Puppeteer" -CertStoreLocation "cert:\CurrentUser\My"

    Get-ChildItem -Path cert:\CurrentUSer\my | where { $_.friendlyname -eq "Puppeteer" } | Export-Certificate -FilePath C:\projects\puppeteer-sharp\lib\PuppeteerSharp.TestServer\testCert.cer

build:
  project: .\lib\PuppeteerSharp.AspNetFramework.sln
  publish_nuget: true
  include_nuget_references: true
  verbosity: minimal
test: off
artifacts:
- path: PuppeteerSharp.AspNetFramework.*.nupkg
  name: PuppeteerSharp.AspNetFramework Package
cache:
  - $HOME/.nuget/packages
