version: 1.0.{build}
image: Ubuntu
configuration: Release
environment:
  git_access_token:
    secure: FxcQ9C8a/NgcQB5dFdZts6ZWEDT4zMhA4qPQAYwWc7huMmhmTIl1sbFEIaAWQMTL
  matrix:
    - framework: netcoreapp2.0

before_build:
- sh: >-
    sudo apt-get -y install gconf-service libasound2 libatk1.0-0 libc6 libcairo2 libcups2 libdbus-1-3 libexpat1 libfontconfig1 libgcc1 libgconf-2-4 libgdk-pixbuf2.0-0 libglib2.0-0 libgtk-3-0 libnspr4 libpango-1.0-0 libpangocairo-1.0-0 libstdc++6 libx11-6 libx11-xcb1 libxcb1 libxcomposite1 libxcursor1 libxdamage1 libxext6 libxfixes3 libxi6 libxrandr2 libxrender1 libxss1 libxtst6 ca-certificates fonts-liberation libappindicator1 libnss3 lsb-release xdg-utils wget

    dotnet restore lib/PuppeteerSharp.sln

    openssl genrsa -des3 -passout pass:12345 -out lib/PuppeteerSharp.TestServer/testCert.key 1024 -noout

    openssl req -new -x509 -key lib/PuppeteerSharp.TestServer/testCert.key -out lib/PuppeteerSharp.TestServer/testCert.cer -passin pass:12345 -subj "/CN=localhost" -outform DER

    sudo openssl x509 -inform der -in lib/PuppeteerSharp.TestServer/testCert.cer -out /usr/local/share/ca-certificates/testCert.crt -outform pem

    sudo update-ca-certificates

    sudo groupadd -r pptruser
    
    sudo useradd -r -g pptruser -G audio,video pptruser 

    sudo chown -R pptruser:pptruser .

    su pptruser

build_script:
- sh: >-
    dotnet build ./lib/PuppeteerSharp.Tests.CloseMe/PuppeteerSharp.Tests.CloseMe.csproj

    dotnet build ./lib/PuppeteerSharp.DevicesFetcher/PuppeteerSharp.DevicesFetcher.csproj

    dotnet build ./lib/PuppeteerSharp.Tests.DumpIO/PuppeteerSharp.Tests.DumpIO.csproj

    dotnet build lib/PuppeteerSharp.TestServer/PuppeteerSharp.TestServer.csproj

    dotnet build ./lib/PuppeteerSharp.Tests/PuppeteerSharp.Tests.csproj

test_script:
- sh: >-
    cd lib/PuppeteerSharp.Tests

    dotnet test -f $framework -s test.runsettings

cache:
  - $HOME/.nuget/packages