name: PushToIntNugetOrg

on:
  workflow_dispatch:

env:
  DOTNET_VERSION: '10.0.x' # The .NET SDK version to use

jobs:
  PushToIntNugetOrg:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 10.0.x
    - name: Install dependencies
      run: |
        dotnet restore lib/PuppeteerSharp.sln
        dotnet dev-certs https -ep lib/PuppeteerSharp.TestServer/testCert.cer
    - name: Build
      run: |
        dotnet build lib/PuppeteerSharp.sln --configuration Release --no-restore
        ls ./lib/PuppeteerSharp/bin/Release
    - name: NugetPush to int.nuget.org
      env:
        NUGET_TOKEN_TEST_EXISTS: ${{ secrets.NUGET_INT_API_KEY }}
      if: env.NUGET_TOKEN_TEST_EXISTS != ''
      run: |
        dotnet nuget push ./lib/PuppeteerSharp/bin/Release/*.nupkg --api-key ${{secrets.NUGET_INT_API_KEY}} --source https://apiint.nugettest.org/v3/index.json
    - name: Build (CDP only)
      run: |
        rm -f ./lib/PuppeteerSharp/bin/Release/*.nupkg
        dotnet build lib/PuppeteerSharp/PuppeteerSharp.csproj /p:DefineConstants=CDP_ONLY /p:Title=PuppeteerSharp.Cdp /p:PackageId=PuppeteerSharp.Cdp /p:Description="Headless Browser .NET API with CDP support only (no WebDriverBiDi)" --configuration Release --no-restore
        ls ./lib/PuppeteerSharp/bin/Release
    - name: NugetPush to int.nuget.org (CDP only)
      env:
        NUGET_TOKEN_TEST_EXISTS: ${{ secrets.NUGET_INT_API_KEY }}
      if: env.NUGET_TOKEN_TEST_EXISTS != ''
      run: |
        dotnet nuget push ./lib/PuppeteerSharp/bin/Release/*.nupkg --api-key ${{secrets.NUGET_INT_API_KEY}} --source https://apiint.nugettest.org/v3/index.json
